FROM nvcr.io/nvidia/pytorch:23.12-py3

RUN pip install langchain langchainhub
RUN pip install langchain_benchmarks langsmith
RUN pip install openai tiktoken chromadb bs4 pandas pyarrow
RUN pip install sentence-transformers
